### ISSUE TITLE
ruby_build provider not implemented as README implies

### ISSUE THREAD

**Issue by colbywhite** [poise/poise-ruby#10]
The README implies that the `:ruby_build` provider is implemented, but it doesn't appear to be. The following recipe results in an error.

```ruby
ruby_runtime 'myapp' do
  provider :ruby_build
  version '2.3.0'
end
```

```
ERROR: No provider found to match 'ruby_build'
```

As expected, looking through the src for both `master` and the `2.1.1` tag, there doesn't appear to actually be any `ruby_build` provider, countering what's in the README.

Is the README just incorrect? Or are you in the process of beginning to use [poise/poise-ruby-build](https://github.com/poise/poise-ruby-build)?

**Comment by coderanger** [comment]
Not sure what you are asking. To quote the only section of the README that mentions the `ruby_build` provider:

> The ruby_build provider uses ruby-build to compile and install Ruby. It can be found in the poise-ruby-build cookbook.

You need that other cookbook, it isn't part of `poise-ruby`.
