### ISSUE TITLE
Specify source for ruby_runtime

### ISSUE THREAD

**Issue by donwlewis** [poise/poise-ruby#12]
I am attempting to install ruby version 2.3 on Red Hat using SLC.  Here is my code for calling the resource:
```ruby
ruby_runtime 'hal' do
  provider :scl
  version '2.3'
end
```

When running this resource, I get the following error:

```shell
================================================================================
           Error executing action `install` on resource 'ruby_runtime[hal]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           ruby_gem[bundler] (/tmp/kitchen/cache/cookbooks/poise-ruby/files/halite_gem/poise_ruby/ruby_providers/base.rb line 109) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2
'
           ---- Begin output of /opt/rh/rh-ruby23/root/usr/bin/gem install "bundler" -q --no-rdoc --no-ri  ----
           STDOUT:
           STDERR: ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
              Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
           ---- End output of /opt/rh/rh-ruby23/root/usr/bin/gem install "bundler" -q --no-rdoc --no-ri  ----
           Ran /opt/rh/rh-ruby23/root/usr/bin/gem install "bundler" -q --no-rdoc --no-ri  returned 2
```

This is most likely due to the fact that our systems can not go out externally to fetch gems.  We have an internal gems server that we leverage, but I am not sure if there is a way to specify a gems source with this resource.

**Comment by coderanger** [comment]
If you're on Chef 13, set `rubygems_url 'https://mygemmirror/'` in your `client.rb` config. Otherwise add `options bundler_version: false` to the `ruby_runtime` resource and it won't try to automatically install Bundler for you. You would need to install it yourself if you want to use `bundle_install` resource later.

**Comment by donwlewis** [comment]
That works for me @coderanger!  Your the best!  I am sure you are going to get tired of me 😄

**Comment by coderanger** [comment]
Hah, no worries :)
