### ISSUE TITLE
reload ruby ohai plugin when run as recipe

### ISSUE THREAD

**Issue by josephholsten** [poise/poise-ruby#3]
People using poise-ruby as a recipe probably want the ruby to be run as their main ruby. So it would be useful to rerun ohai's ruby plugin, presumably after adding setting `$PATH`. e.g.

```ruby
include_recipe 'poise-ruby'

poise_ruby_path = "/opt/#{node['poise-ruby']['ruby']}/bin"
ENV['PATH'] = "#{poise_ruby_path}:#{ENV['PATH']}"

execute 'add poise-ruby to /etc/environment' do
  command <<-EOS
    TEMP=`mktemp -t environment.XXXXXXXXXX` || exit 1
    cat /etc/environment |
    sed 's/PATH=.*$/PATH="#{ENV['PATH'].gsub('/','\/')}"/' > $TEMP &&
    cat $TEMP > /etc/environment
    rm $TEMP
  EOS

  not_if "grep 'PATH=.*#{poise_ruby_path}'  /etc/environment"
end

ohai 'ruby' do
  plugin 'ruby'
  action :reload
end
```

I've had to use this terrible hack to allow the [`passenger_apache2`](https://github.com/opscode-cookbooks/passenger_apache2) cookbook to auto discover the right ruby.

**Comment by coderanger** [comment]
Closing old tickets as this cookbook has pivoted.
