### ISSUE TITLE
rubygems 2.2.2

### ISSUE THREAD

**Issue by iroller** [poise/poise-ruby#4]
Hi there,

Any plans on releasing newer ruby&rubygems for ruby.poise.io? I'm currently stuck with trying to upgrade poise/berkshelf-api cookbook to use the latest berkshelf-api because rubygems 2.2.0 are buggy and go into indefinite loop on gem install.

Would you recommend waiting for newer packages, switching to another cookbook or patching poise/berkshelf-api to use another cookbook to build ruby?

**Comment by coderanger** [comment]
I'm no longer making new Ruby builds as I don't have the resources to keep that up. New cookbook reflects this.
